simplesocial/groups/urls.py
from django.conf.urls import url
from . import views

app_name = 'groups'

urlpatterns = [
    url(r'^$',views.ListGroups.as_view(),name='all'),
    url(r'^new/$',views.CreateGroup.as_view(),name='create'),
    url(r'^posts/in/(?P<slug>[-\w]+)/$',views.SingleGroup.as_view(),name='single'),
    url(r'^join/(?P<slug>[-\w]+)/$',views.JoinGroup.as_view(),name='join'),
    url(r'^leave/(?P<slug>[-\w]+)/$',views.LeaveGroup.as_view(),name='leave'),
]

simplesocial/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'^new/$',views.CreatePost.as_view(),name='create'),
    url(r'^by/(?P<username>[-\w]+)/$',views.UserPosts.as_view(),name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
]

simplesocial/groups/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
import misaka
from django.urls import reverse 

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group','user')

simplesocial/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from . models import Group, GroupMember
from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.db import IntegrityError
# Create your views here.
from .  import models

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError :
            messages.warning(self.request,'warning, already a member')
        else:
            messages.success(self.request,'You are now a member')

        return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):

        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are not in this group!')
        else:
            membership.delete()
            messages.success(self.request,'You have left the group!')

        return super().get(request,*args,**kwargs)

simplesocial/groups/templates/groups/group_base.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        {% block pregroup %} {% endblock %}
        {% block group_content %} {% endblock %}
        {% block postgroup %} {% endblock %}
    </div>
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}

<style>
.zoom {
  padding: 5px;
  
  transition: transform .2s;
  margin: 0 auto;
}
.zoom:hover {
  -ms-transform: scale(1.05); /* IE 9 */
  -webkit-transform: scale(1.05); /* Safari 3-8 */
  transform: scale(1.05); 
}
</style>

<div class="col-md-4">
    <h1> <b>{{ group.name }}</b>  </h1>
    <h2>Members Count : <span class="label label-default">{{ group.members.count }}</span></h2>
    <div class="content">
        {% if user in group.members.all %}
            <div class="zoom">
            <a href="{% url 'groups:leave' slug=group.slug %}"
            class="btn btn-lg btn-fill btn-warning">
            <span class="glyphicon glyphicon-remove-circle "></span> Leave </a>
            </div>
            
        {% else  %}
            <div class="zoom">
            <a href="{% url 'groups:join' slug=group.slug %}"
            class="btn btn-lg btn-fill btn-success">
            <span class="glyphicon glyphicon-ok-circle "></span> Join </a>
            </div>
            
        {% endif %}
    </div>
</div>

{% endblock %}

{% block group_content %}


<style>
.zoom {
  padding: 5px;
  
  transition: transform .2s;
  margin: 0 auto;
}
.zoom:hover {
  -ms-transform: scale(1.05); /* IE 9 */
  -webkit-transform: scale(1.05); /* Safari 3-8 */
  transform: scale(1.05); 
}

#myBtn {
  display: none;
  position: fixed;
  bottom: 20px;
  left: 30px;
  z-index: 99;
  font-size: 18px;
  border: none;
  outline: none;
  background-color: grey;
  color: white;
  cursor: pointer;
  padding: 15px;
  border-radius: 4px;
}

#myBtn:hover {
  background-color: #555;
}


</style>


<div class="col-md-8">
    {% if group.posts.count is 0 %}
        <h2>No posts in this group yet!</h2>
    {% else %}
        {% for post in group.posts.all %}
            {% include "posts/_post.html" %}
        {% endfor %}
    {% endif %}
</div>


<button onclick="topFunction()" id="myBtn" title="Go to top">Top <span class="glyphicon glyphicon-arrow-up"></span></button>

<script>
 
var myButton = document.querySelector("#myBtn");

window.scrollTo({
  top: 0,
  left: 0,
  behavior: 'smooth'
});

window.onscroll = function() {scrollFunction()};

function scrollFunction(){
    if(document.body.scrollTop > 20 || document.documentElement.scrollTop > 20){
        myButton.style.display = "block";
    }
    else{
        myButton.style.display = "none";
    }
}

function topFunction(){
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
}

</script>




{% endblock %}

simplesocial/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<div class="jumbotron">
    <h4>Create a new group</h4>
    <form action="{% url 'groups:create' %}" method="post" id="groupForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary btn-larg" value="Create">
    </form>
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}

<style>
* {
  box-sizing: border-box;
}

#myInput {
  background-image: url('/css/searchicon.png');
  background-position: 10px 12px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}

#myUL {
  list-style-type: none;
  padding: 0;
  margin: 0;
}

#myUL li a {
  border: 1px solid #ddd;
  margin-top: -1px; /* Prevent double borders */
  background-color: #f6f6f6;
  padding: 12px;
  text-decoration: none;
  font-size: 18px;
  color: black;
  display: block
}

#myUL li a:hover:not(.header) {
  background-color: #eee;
}

.zoom {
  padding: 0px;
  
  transition: transform .2s;
  margin: 0 auto;
}
.zoom:hover {
  -ms-transform: scale(1.05); /* IE 9 */
  -webkit-transform: scale(1.05); /* Safari 3-8 */
  transform: scale(1.05); 
}
</style>

    <div class="col-md-4">
        <div class="content">
            {% if user.is_authenticated %}
                <h2>  <b>Welcome Back!</b>
                <a href="{% url 'posts:for_user' username=user.username %}"> @{{user.username}} </a>
                </h2>
            {% endif %}

            <h2>Groups..</h2>
            <h2>Welcome to the groups page!</h2>
        </div>
        <br>
        {% if user.is_authenticated %}
            <div class="zoom"> 
                <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning" >
            <span class="glyphicon glyphicon-plus-sign "></span> Create New Group </a>
            </div>
            
        {% endif %}

        <br>
        <br>
        


    </div>

<script>

</script>


{% endblock %}



{% block group_content %}



<style>
.zoom {
  padding: 5px;
  
  transition: transform .2s;
  margin: 0 auto;
}
.zoom:hover {
  -ms-transform: scale(1.03); /* IE 9 */
  -webkit-transform: scale(1.03); /* Safari 3-8 */
  transform: scale(1.03); 
}

#myBtn {
  display: none;
  position: fixed;
  bottom: 40px;
  left: 40px;
  z-index: 99;
  font-size: 18px;
  border: none;
  outline: none;
  background-color: grey;
  color: white;
  cursor: pointer;
  padding: 15px;
  border-radius: 4px;
}

#myBtn:hover {
  background-color: #555;
}


</style>



    <br>
    
    <div class="col-md-8">
        <div class="list-group jumbotron" id="myList">
            {% for group in object_list %}

            <div class="zoom">
                <a class="list-group-item  " href="{% url 'groups:single' slug=group.slug %}">
                    <h3 class="title list-group-item-heading" ><b> {{group.name}} </b> </h3>
                    <div class="list-group-item-text container-fluid">
                        {{ group.description_html|safe }}
                        <div class="row">
                            <div class="col-md-4">
                                <span class="badge" >{{group.members.count}}</span>
                                member{{group.members.count|pluralize}}
                            </div>
                            <div class="col-md-4">
                                <span class="badge" >{{group.posts.count}}</span>
                                post{{group.posts.count|pluralize}}
                            </div>
                        </div>
                    </div>
                </a>
                <br>
                <br>
            </div>   
            {% endfor %}
        </div>
    </div>


    <button onclick="topFunction()" id="myBtn" title="Go to top">Top <span class="glyphicon glyphicon-arrow-up"></span></button>

<script>
 
var myButton = document.querySelector("#myBtn");

window.scrollTo({
  top: 0,
  left: 0,
  behavior: 'smooth'
});

window.onscroll = function() {scrollFunction()};

function scrollFunction(){
    if(document.body.scrollTop > 20 || document.documentElement.scrollTop > 20){
        myButton.style.display = "block";
    }
    else{
        myButton.style.display = "none";
    }
}

function topFunction(){
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
}

</script>

{% endblock %}